version: "1.0"
info:
  model: int-scaffold
packages:
- name: FR_STT_iPaaSProject
  gitServerName: fr_stt_github
  gitUrl: https://github.com/staillanibm
  gitUsername: staillanibm
  gitBranch: main
- name: WmJDBCAdapter
  version: 10.3.0.0.34
  wpmServer: https://packages.webmethods.io
  wpmRegistry: licensed
- name: sttHelloWorld
  version: "1.0"
  gitServerName: fr_stt_github
  gitUrl: https://github.com/staillanibm
  gitUsername: staillanibm
  gitBranch: main
- name: sttGlobalVariables
  version: "1.0"
  gitServerName: fr_stt_github
  gitUrl: https://github.com/staillanibm
  gitUsername: staillanibm
  gitBranch: main
- name: WmSalesforceRESTProvider
  wpmServer: https://packages.webmethods.io
  wpmRegistry: supported
services:
- serviceName: project.fr_stt_ipaas.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections:Database_1
  packages:
  - name: FR_STT_iPaaSProject
    version: "1.0"
  - name: sttGlobalVariables
    version: "1.0"
  - name: sttHelloWorld
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
  - name: WmSalesforceRESTProvider
    version: 10.7.0.0.187
- serviceName: project.fr_stt_ipaas.WmSalesforceRESTProvider.com_softwareag_cloudstreams_salesforce_rest_v60.connections:SalesforceV2
  packages:
  - name: FR_STT_iPaaSProject
    version: "1.0"
  - name: sttGlobalVariables
    version: "1.0"
  - name: sttHelloWorld
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
  - name: WmSalesforceRESTProvider
    version: 10.7.0.0.187
- serviceName: project.fr_stt_ipaas.integrations:getFibo
  packages:
  - name: FR_STT_iPaaSProject
    version: "1.0"
  - name: sttGlobalVariables
    version: "1.0"
  - name: sttHelloWorld
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
  - name: WmSalesforceRESTProvider
    version: 10.7.0.0.187
- serviceName: sttHelloWorld.eu.sttlab.services:getFibo
  packages:
  - name: sttHelloWorld
    version: "1.0"
- serviceName: sttHelloWorld.eu.sttlab.services.java:calculateFibo
  packages:
  - name: sttHelloWorld
    version: "1.0"
- serviceName: project.fr_stt_ipaas.integrations:listAccounts
  packages:
  - name: FR_STT_iPaaSProject
    version: "1.0"
  - name: sttGlobalVariables
    version: "1.0"
  - name: sttHelloWorld
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
  - name: WmSalesforceRESTProvider
    version: 10.7.0.0.187
- serviceName: sttHelloWorld.eu.sttlab.services:getAccounts
  packages:
  - name: sttHelloWorld
    version: "1.0"
- serviceName: sttHelloWorld.eu.sttlab.services.salesforce:listAccounts
  packages:
  - name: sttHelloWorld
    version: "1.0"
- serviceName: project.fr_stt_ipaas.integrations:listAccountsV2
  packages:
  - name: FR_STT_iPaaSProject
    version: "1.0"
  - name: sttGlobalVariables
    version: "1.0"
  - name: sttHelloWorld
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
  - name: WmSalesforceRESTProvider
    version: 10.7.0.0.187
- serviceName: project.fr_stt_ipaas.WmSalesforceRESTProvider.com_softwareag_cloudstreams_salesforce_rest_v60.operations.actions:queryAccounts
  packages:
  - name: FR_STT_iPaaSProject
    version: "1.0"
  - name: sttGlobalVariables
    version: "1.0"
  - name: sttHelloWorld
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
  - name: WmSalesforceRESTProvider
    version: 10.7.0.0.187
- serviceName: project.fr_stt_ipaas.integrations:processUsers
  packages:
  - name: FR_STT_iPaaSProject
    version: "1.0"
  - name: sttGlobalVariables
    version: "1.0"
  - name: sttHelloWorld
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
  - name: WmSalesforceRESTProvider
    version: 10.7.0.0.187
- serviceName: sttHelloWorld.eu.sttlab.services:processUsers
  packages:
  - name: sttHelloWorld
    version: "1.0"
- serviceName: sttHelloWorld.eu.sttlab.services.s3:readFile
  packages:
  - name: sttHelloWorld
    version: "1.0"
- serviceName: pub.io:streamToString
  packages:
  - name: WmPublic
    version: 11.1.0.0.2064
- serviceName: pub.json:jsonToDocument
  packages:
  - name: WmPublic
    version: 11.1.0.0.2064
- serviceName: pub.date:getCurrentDate
  packages:
  - name: WmPublic
    version: 11.1.0.0.2064
- serviceName: sttHelloWorld.eu.sttlab.services.jdbc.sqlserver:insertUser
  packages:
  - name: sttHelloWorld
    version: "1.0"
- serviceName: project.fr_stt_ipaas.integrations:sayHello
  packages:
  - name: FR_STT_iPaaSProject
    version: "1.0"
  - name: sttGlobalVariables
    version: "1.0"
  - name: sttHelloWorld
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
  - name: WmSalesforceRESTProvider
    version: 10.7.0.0.187
- serviceName: project.fr_stt_ipaas.integrations:syncAccountsWithERP
  packages:
  - name: FR_STT_iPaaSProject
    version: "1.0"
  - name: sttGlobalVariables
    version: "1.0"
  - name: sttHelloWorld
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
  - name: WmSalesforceRESTProvider
    version: 10.7.0.0.187
configurationVariables:
  ? cloudstreamsconnection.project..fr_stt_ipaas..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:SalesforceV2.cn.providerUrl
  : https://orgfarm-94e92d9500-dev-ed.develop.my.salesforce.com
  ? artConnection.FR_STT_iPaaSProject.project.fr_stt_ipaas.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionManagerSettings.startupBackoffSecs
  : "10"
  ? artConnection.FR_STT_iPaaSProject.project.fr_stt_ipaas.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionManagerSettings.heartBeatInterval
  : "0"
  ? cloudstreamsconnection.project..fr_stt_ipaas..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:SalesforceV2.expireTimeout
  : "1000"
  ? cloudstreamsconnection.project..fr_stt_ipaas..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:SalesforceV2.maximumPoolSize
  : "10"
  ? artConnection.FR_STT_iPaaSProject.project.fr_stt_ipaas.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.keyStore
  : ""
  ? cloudstreamsconnection.project..fr_stt_ipaas..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:SalesforceV2.poolable
  : "true"
  ? cloudstreamsconnection.project..fr_stt_ipaas..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:SalesforceV2.cn.retryIfRequestSentOk
  : "true"
  ? cloudstreamsconnection.project..fr_stt_ipaas..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:SalesforceV2.cx.grant_type
  : refresh_token
  ? artConnection.FR_STT_iPaaSProject.project.fr_stt_ipaas.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.user
  : sttlab
  ? cloudstreamsconnection.project..fr_stt_ipaas..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:SalesforceV2.oauth_v20.authorizationHeaderInTokenRefresh
  : "false"
  ? cloudstreamsconnection.project..fr_stt_ipaas..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:SalesforceV2.poolIncrementSize
  : "1"
  ? cloudstreamsconnection.project..fr_stt_ipaas..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:SalesforceV2.cn.keepAliveInterval
  : "300000"
  ? cloudstreamsconnection.project..fr_stt_ipaas..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:SalesforceV2.oauth_v20.refreshToken
  : "{AES}hL8P5n6/+jhXtM1uxmCL3/ffnqRTB5NhOOwfCUFwxJqcBv4m8JMtLN0gab7W36kLRMJTS3wydy1GRBJy4HgI0oHWYSMh/nJDEKMZXRd/f7Huydkdxz5CebROyImJldqb"
  ? artConnection.FR_STT_iPaaSProject.project.fr_stt_ipaas.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.datasourceClass
  : com.wm.dd.jdbcx.sqlserver.SQLServerDataSource
  ? cloudstreamsconnection.project..fr_stt_ipaas..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:SalesforceV2.oauth.consumerId
  : 3MVG9dAEux2v1sLuFxnd1N_bXrRevKDz6OBgc4fIbBNTZ6iFStgrz62wNis2FflozuJIDrpZAhz6OaSHlJLLR
  ? cloudstreamsconnection.project..fr_stt_ipaas..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:SalesforceV2.connectionEnabled
  : "true"
  ? cloudstreamsconnection.project..fr_stt_ipaas..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:SalesforceV2.cn.enableSNI
  : "true"
  ? iscloudstreamsconnectorservice.project..fr_stt_ipaas..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..operations..actions:queryAccounts.virtualServiceName
  : WmCloudStreams.RestVS
  ? artConnection.FR_STT_iPaaSProject.project.fr_stt_ipaas.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionManagerSettings.poolIncrementSize
  : "1"
  ? cloudstreamsconnection.project..fr_stt_ipaas..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:SalesforceV2.oauth_v20.authenticationServerUrl
  : https://login.salesforce.com/services/oauth2/token
  ? artConnection.FR_STT_iPaaSProject.project.fr_stt_ipaas.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.transactionType
  : NO_TRANSACTION
  ? cloudstreamsconnection.project..fr_stt_ipaas..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:SalesforceV2.oauth_v20.authorizationServerUrl
  : https://login.salesforce.com/services/oauth2/authorize
  ? cloudstreamsconnection.project..fr_stt_ipaas..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:SalesforceV2.oauth_v20.authorizationHeaderPrefix
  : Bearer
  ? cloudstreamsconnection.project..fr_stt_ipaas..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:SalesforceV2.cn.sockBuffSize
  : "8192"
  ? artConnection.FR_STT_iPaaSProject.project.fr_stt_ipaas.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.driverType
  : Progress® DataDirect®
  ? artConnection.FR_STT_iPaaSProject.project.fr_stt_ipaas.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.databaseName
  : sqldb
  ? cloudstreamsconnection.project..fr_stt_ipaas..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:SalesforceV2.startupRetryCount
  : "0"
  ? cloudstreamsconnection.project..fr_stt_ipaas..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:SalesforceV2.timeoutType
  : auto
  ? cloudstreamsconnection.project..fr_stt_ipaas..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:SalesforceV2.blockTimeout
  : "1000"
  ? cloudstreamsconnection.project..fr_stt_ipaas..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:SalesforceV2.cn.idleTimeout
  : "-1"
  ? cloudstreamsconnection.project..fr_stt_ipaas..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:SalesforceV2.cn.enableCompression
  : "false"
  ? cloudstreamsconnection.project..fr_stt_ipaas..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:SalesforceV2.cn.tcpNoDelay
  : "false"
  ? cloudstreamsconnection.project..fr_stt_ipaas..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:SalesforceV2.cn.retryCount
  : "4"
  ? artConnection.FR_STT_iPaaSProject.project.fr_stt_ipaas.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionManagerSettings.maximumPoolSize
  : "10"
  ? iscloudstreamsconnectorservice.project..fr_stt_ipaas..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..operations..actions:queryAccounts.connectionAlias
  : project.fr_stt_ipaas.WmSalesforceRESTProvider.com_softwareag_cloudstreams_salesforce_rest_v60.connections:SalesforceV2
  ? cloudstreamsconnection.project..fr_stt_ipaas..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:SalesforceV2.cn.validateAfterInactivity
  : "1000"
  ? cloudstreamsconnection.project..fr_stt_ipaas..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:SalesforceV2.cn.connectTimeout
  : "30000"
  ? cloudstreamsconnection.project..fr_stt_ipaas..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:SalesforceV2.cn.hostnameVerifier
  : org.apache.http.conn.ssl.DefaultHostnameVerifier
  ? artConnection.FR_STT_iPaaSProject.project.fr_stt_ipaas.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.dbType
  : MSSQL
  ? artConnection.FR_STT_iPaaSProject.project.fr_stt_ipaas.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.networkProtocol
  : ""
  ? artConnection.FR_STT_iPaaSProject.project.fr_stt_ipaas.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionManagerSettings.minimumPoolSize
  : "1"
  ? cloudstreamsconnection.project..fr_stt_ipaas..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:SalesforceV2.cn.socketStaleCheck
  : "true"
  ? cloudstreamsconnection.project..fr_stt_ipaas..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:SalesforceV2.startupBackoffSecs
  : "10"
  ? artConnection.FR_STT_iPaaSProject.project.fr_stt_ipaas.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionManagerSettings.poolable
  : "true"
  ? artConnection.FR_STT_iPaaSProject.project.fr_stt_ipaas.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.serverName
  : sttlab.database.windows.net
  ? cloudstreamsconnection.project..fr_stt_ipaas..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:SalesforceV2.cn.socketLinger
  : "-1"
  ? artConnection.FR_STT_iPaaSProject.project.fr_stt_ipaas.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionManagerSettings.startupRetryCount
  : "0"
  ? artConnection.FR_STT_iPaaSProject.project.fr_stt_ipaas.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionManagerSettings.expireTimeout
  : "1000"
  ? cloudstreamsconnection.project..fr_stt_ipaas..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:SalesforceV2.cn.reuseAddr
  : "false"
  ? cloudstreamsconnection.project..fr_stt_ipaas..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:SalesforceV2.oauth.accessToken
  : "{AES}vnu4mfjy3wQ2SaQzMDm96slu/ogc+m0fF6/O1S6ZpTVbi999Ix5WSODL9/oMUsgl345bM7qDlMnyXfAIftt6TiudSXfYKxPwerFFn/lfhDA7iXZBs5P1DUUbdtxmqDVmxyihS3c0/AxuUEye7/7SqGmK1wuN3U1rA1B0VhuZoUw="
  ? cloudstreamsconnection.project..fr_stt_ipaas..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:SalesforceV2.oauth.consumerSecret
  : "{AES}TZM+ssmCoWnWo25N1h7b2hFfNkaShIiABrV0pGBaDYOybMjiLOevW+wGW/sIbrgxlMLqC1vaoIw2JG/XzC0QbGmK1wuN3U1rA1B0VhuZoUw="
  ? cloudstreamsconnection.project..fr_stt_ipaas..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:SalesforceV2.oauth_v20.accessTokenRefreshURL
  : https://login.salesforce.com/services/oauth2/token
  ? cloudstreamsconnection.project..fr_stt_ipaas..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:SalesforceV2.oauth_v20.accessTokenRefreshURLRequest
  : URL Query String
  ? cloudstreamsconnection.project..fr_stt_ipaas..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:SalesforceV2.minimumPoolSize
  : "1"
  ? cloudstreamsconnection.project..fr_stt_ipaas..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:SalesforceV2.cn.readTimeout
  : "30000"
  ? artConnection.FR_STT_iPaaSProject.project.fr_stt_ipaas.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.trustStore
  : ""
  ? cloudstreamsconnection.project..fr_stt_ipaas..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:SalesforceV2.oauth_v20.instanceURL
  : https://orgfarm-94e92d9500-dev-ed.develop.my.salesforce.com
  ? cloudstreamsconnection.project..fr_stt_ipaas..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:SalesforceV2.oauth_v20.scope
  : offline_access api refresh_token
  ? artConnection.FR_STT_iPaaSProject.project.fr_stt_ipaas.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionManagerSettings.blockingTimeout
  : "1000"
  ? artConnection.FR_STT_iPaaSProject.project.fr_stt_ipaas.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.portNumber
  : "1433"
  ? artConnection.FR_STT_iPaaSProject.project.fr_stt_ipaas.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionEnabled
  : "true"
  ? artConnection.FR_STT_iPaaSProject.project.fr_stt_ipaas.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.otherProperties
  : loginTimeout=60;
  ? cloudstreamsconnection.project..fr_stt_ipaas..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:SalesforceV2.oauth_v20.refreshAccessToken
  : "true"
  ? artConnection.FR_STT_iPaaSProject.project.fr_stt_ipaas.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.password
  : "{AES}xQJbA1N3SVslXYLJd7vQXHtoPSIUr5vmkgNS5mqAKjw="
